
// we import useParams because we need to get the product ID from the URL
import { useParams } from "react-router-dom";   

// we import the custom hook generated by RTK Query to fetch product details by ID
import { useGetProductByIdQuery } from "../apis/ProductApi.jsx";

// we import useDispatch to dispatch actions to the Redux store
import { useDispatch } from "react-redux";

// we import the addToCart action to add the product to the cart
import { addToCart } from "../component/MyProduct.jsx";

// we use arror funtion to define the ProductDetails component because it is more concise that is easier to read
const ProductDetails = () => {

    // id was inside curly braces because useParams returns an object with key as the parameter name and value as the parameter value
    const { id } = useParams();

    //we put id inside the custom hook to fetch the product details
    const { data, error, isLoading } = useGetProductByIdQuery(id);

    // we create a dispatch function to dispatch actions to the Redux store
    const dispatch = useDispatch();

    if (isLoading) return <div>Loading...</div>;
    if (error) return <div>Error loading product details.</div>;
    return (
        <div className="p-6">
            <img src={data.thumbnail} alt={data.title} className="w-96 h-96 object-cover mx-auto" />
            <h1 className="text-3xl font-bold mt-4">{data.title}</h1>
            <p className="text-gray-700 mt-2">{data.description}</p>

            <button
                onClick={() => dispatch(addToCart(data))}
                className="mt-4 bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-600"
            >
                Add to Cart
            </button>
        </div>
    );
}
export default ProductDetails;