//we import createApi and fetchBaseQuery because they are essential(that is the core of RTK Query) for defining an API service.
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';

// We define the productsApi using createApi function from RTK Query.
export const productsApi = createApi({
    // reducerPath is a unique key that identifies the API effect in the Redux store.
    // baseQuery is a function that defines how to fetch data from the server.
    // endpoints is a function that defines the different operations (queries and mutations) we can perform with this API.
    // baseUrl is set to 'https://dummyjson.com', which is the base URL for all API requests.
    // The endpoints defined here include fetching all products, fetching a product by ID, fetching products by category, and searching for products.
    // Each endpoint uses builder.query to define a query operation.
    // all tgis keys are from the dummyjson API documentation.
    // transformResponse is used to extract the relevant data from the API response.
    // Finally, we export hooks generated by RTK Query for each endpoint to use in our React components.
    // These hooks allow us to easily fetch data and manage loading and error states in our components.
    // Overall, this file sets up a structured way to interact with the products API using Redux Toolkit Query.
    // build.query is used to define a query endpoint.
    // we export the auto-generated hooks for each endpoint for use in React components.
  reducerPath: 'productsApi',
  baseQuery: fetchBaseQuery({
    baseUrl: 'https://dummyjson.com',
  }),
  endpoints: (builder) => ({
    getAllProducts: builder.query({
      query: (limit = 30) => ({
        url: '/products',
        params: { limit },
      }),
      transformResponse: (response) => response.products,
    }),
    getProductById: builder.query({
      query: (id) => `/products/${id}`,
    }),
    getProductsByCategory: builder.query({
      query: (category) => ({
        url: '/products/category/' + category,
      }),
      transformResponse: (response) => response.products,
    }),
    searchProducts: builder.query({
      query: (searchTerm) => ({
        url: '/products/search',
        params: { q: searchTerm },
      }),
      transformResponse: (response) => response.products,
    }),
  }),
});

export const {
  useGetAllProductsQuery,
  useGetProductByIdQuery,
  useGetProductsByCategoryQuery,
  useSearchProductsQuery,
} = productsApi;
